# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"draw_img": "01-svg-helpers.ipynb",
         "vis_graphic": "01-svg-helpers.ipynb",
         "draw_background": "01-svg-helpers.ipynb",
         "draw_border": "01-svg-helpers.ipynb",
         "draw_circle_fill": "01-svg-helpers.ipynb",
         "draw_sun": "02-solar-system.ipynb",
         "select_new_colour": "02-solar-system.ipynb",
         "draw_orbit_path": "02-solar-system.ipynb",
         "draw_line_path": "02-solar-system.ipynb",
         "get_planet_size_center": "02-solar-system.ipynb",
         "draw_planets": "02-solar-system.ipynb",
         "add_noise": "02-solar-system.ipynb",
         "draw_solar_system": "02-solar-system.ipynb",
         "load_img_data": "03-scenery-dither.ipynb",
         "rgb_to_bw": "03-scenery-dither.ipynb",
         "change_resolution": "03-scenery-dither.ipynb",
         "scale_pixel_intensity": "03-scenery-dither.ipynb",
         "get_img_negative": "03-scenery-dither.ipynb",
         "process_img": "03-scenery-dither.ipynb",
         "draw_scenery_dither": "03-scenery-dither.ipynb",
         "generate_world": "06-perlin-noise.ipynb",
         "get_dist_to_coords": "06-perlin-noise.ipynb",
         "add_color_mask": "06-perlin-noise.ipynb",
         "get_coord_dist_weights": "06-perlin-noise.ipynb",
         "weight_world": "06-perlin-noise.ipynb",
         "generate_weighted_coloured_world": "06-perlin-noise.ipynb"}

modules = ["svg.py",
           "solar.py",
           "scenery.py",
           "world.py"]

doc_url = "https://AyrtonB.github.io/genart/"

git_url = "https://github.com/AyrtonB/Generative-Art"

def custom_doc_links(name): return None
