# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"vis_graphic": "01-solar-system.ipynb",
         "draw_img": "01-solar-system.ipynb",
         "select_new_colour": "01-solar-system.ipynb",
         "draw_background": "01-solar-system.ipynb",
         "draw_circle_fill": "01-solar-system.ipynb",
         "draw_sun": "01-solar-system.ipynb",
         "draw_orbit": "01-solar-system.ipynb",
         "draw_line": "01-solar-system.ipynb",
         "get_planet_size_center": "01-solar-system.ipynb",
         "draw_planets": "01-solar-system.ipynb",
         "draw_border": "01-solar-system.ipynb",
         "add_noise": "01-solar-system.ipynb"}

modules = ["solar.py"]

doc_url = "https://AyrtonB.github.io/genart/"

git_url = "https://github.com/AyrtonB/Generative-Art"

def custom_doc_links(name): return None
