name: GenArt

channels:
  - conda-forge
  - fastai
  
dependencies:
  - python=3.7
  - pandas
  - matplotlib
  - jupyterlab
  - seaborn
  - nbdev
  - pycairo
  - cairosvg
  - pip
  
  - pip:
      - ipypb
      - feautils